### ISSUE TITLE
How to use Openfire plugin?

### ISSUE THREAD

**Issue by koshkamau** [guusdk/httpfileuploadcomponent#11]
I wonder, how to use this component with Openfire server.
When I read the plugin description in admin console it seems that everything should work without my interference. But it doesn't.

I installed openfire plugin "Http file upload" and can't see any changes in admin console except one new row about installed plugin. No new ports in server information no new records in external components.
I also don't see any new listening sockets in netstat.

I'm trying to send a file from Psi+ to Conversations.
In XML console I see this:

```
<iq from='koshkamau@koshka.ddns.net' id='aae6a' to='httpfileupload.koshka.ddns.net' type='get'><request xmlns='urn:xmpp:http:upload'><filename>DSC03184.jpg</filename><size>796982</size><content-type>image/jpeg</content-type></request></iq>

<iq id="aae6a" from="httpfileupload.koshka.ddns.net" type="result" to="koshkamau@koshka.ddns.net/Psi+">
<slot xmlns="urn:xmpp:http:upload">
<put>https://koshka.ddns.net:7443/httpfileupload/b80a76af-7b32-4393-9a3d-cc42cb7f9751/DSC03184.jpg</put>
<get>https://koshka.ddns.net:7443/httpfileupload/b80a76af-7b32-4393-9a3d-cc42cb7f9751/DSC03184.jpg</get>
</slot>
</iq>
```

After which I get message "Upload failed connection refused". Perhaps it means that nobody is listening port 7443. Why? 
And why 7443? I didn't see this number anywhere.
Why the plugin works to invite client to send file but doesn't work to actually receive it?

Or maybe description inside Openfire is misleading and I should use the way described here: run as a separate service and manually registering it as a external component in Openfire?

**Comment by guusdk** [comment]
Many questions! Let me try to answer them one by one.

First a bit of background: there are two different products:

- the HTTP File Upload Component (this project on Github)
- a HTTP File Upload plugin (part of the Openfire source code)

Both projects share a lot of code, but are different. The (external) component, this project, is ment to run as a stand-alone process that connects as an external component to Openfire. The plugin, on the other hand, runs in Openfire internally. They both provide the same services.

You are right to conclude that the plugin does not add a page to the Openfire admin console. This is because in the current implementation, there is very little that you can configure (so I was lazy and did not create an admin page).

It's running on port 7443 (by default), because it is using the same web server that Openfire uses for HTTP binding (BOSH). That, by default, uses 7443.

Given the XMPP output that you provided, the code was running at least somewhat successfully (the slot assignment is done by the HTTP File Upload code.

I can't say for sure why you can't connect. I suspect a network or firewall issue. Maybe check if the HTTP Bind service of Openfire is enabled (I'm not sure if that's required, but it's good to check, just to be sure).

**Comment by koshkamau** [comment]
Thank you very much. 
I didn't expect a reply at all, let alone so soon so my message was more about complaining after the night of attempts to make this plugin work.
With BOSH enabled in admin console (and its port 7443 opened) everything works as expected.

I was completely unaware about BOSH and its significance in contemporary jabber world.
I get used to use File transfer proxy (SOCKS5 bytestreams, proxy65) and now am forced to use http file upload because nobody supports proxy65 on mobile apps anymore.

Perhaps, plugin doesn't require any controls in admin interface but ,in my opinion, it is worth mentioning in  help file that the plugin depends on BOSH.
I expected that plugin would create web server himself and would open listening port. I didn't see such a port in netstat so I thought that plugin is broken and my next planned step was to try ejabberd, where I saw enough levers to try to make it work.

**Comment by guusdk** [comment]
The dependency on BOSH (HTTP-Bind) is unintentional, to be honest. That needs fixing in Openfire. And, yes, you're absolutely right, but, so many tasks, so little time. If you're up for it, try contributing - if only a change in the documentation, that would be very welcome!
