### ISSUE TITLE
Is jetty mandatory and other questions ...

### ISSUE THREAD

**Issue by ErwanF76** [guusdk/httpfileuploadcomponent#26]
Hi !

I need some clarifications :)

A short summary of my settings:
- 2 Openfire servers running into 2 differents domains;
- 2 Converse.js clients running at each extremities.
That gives:
Client 1 (converse.js) <-> Openfire@domain1.org <-> Openfire@domain2.org <-> Client 2 (converse.js)
Everything works fine (chat, group chat, HTTP-upload thx to the dedicated plug-in).

For some reasons, I would like to use distinct ports for Chat and HTTP-upload.
I noticed that I could configure the HTTP-upload plug-in using the properties below:
- plugin.httpfileupload.announcedWebHost -> DNS name of the local Openfire server
- plugin.httpfileupload.announcedWebPort -> 7444 (port different from 7443)
The new port is taken into account by the attempt of transfer (could see that in Openfire logs), unfortunately the port is not actually opened on Openfire host :(
Is this the expected behaviour ?

I tried to use an Nginx as external Web server (running on another machine).
But I noticed that some dependencies from Jetty are somehow hardcoded in the source code of the httpfileuploadcomponent.
In addition, when trying to upload files from Converse.js, the intermediate UUID sub-folder (in the upload path) is not created in the target web context root folder 'httpfileupload' hosted by the Nginx server.
My understanding is that I can't run another Web server than Jetty, the one embedded into Openfire server. No chance to run another type of Web server as Nginx, and on another server than Openfire.
Do you confirm ?

Many many thx for your clarification.
KR
ErwanF

**Comment by hamzaozturk** [comment]
You need to set some header parameters for converse.js to be worked.

```
server {
    listen 80;
    listen [::]:80;
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name upload.example.com;

    ssl_certificate /root/certificate/fullchain.pem;
    ssl_certificate_key /root/certificate/privkey.pem;

    client_max_body_size 50m;

    location / {
            add_header Access-Control-Allow-Origin '*';
            add_header Access-Control-Allow-Methods 'PUT, GET, OPTIONS, HEAD';
            add_header Access-Control-Allow-Headers 'Authorization, Content-Type';
            add_header Access-Control-Allow-Credentials 'true';

            proxy_pass http://%ip_address%:12121;
    }
}

```

**Comment by guusdk** [comment]
This project (unlike the very similar project that wraps all this in an Openfire plugin) can be ran as a stand-alone instance. If it is running as such, it needs to have some kind of webserver that can handle the HTTP-part of the functionality. For this, an embedded Jetty server is launched (when running as an Openfire plugin, the Jetty webserver that is provided by Openfire is used).

You can configure the directory that is used to store files using the `fileRepo` option in the launcher, or use the `plugin.httpfileupload.fileRepo` system property when running as a plugin in Openfire. When you are converging multiple instances of this project under one URL, you must make sure that all instances use the same file repository: otherwise parts of the content will appear to be 'missing', depending on what instance is being used.
