### ISSUE TITLE
Getting port as part of upload and download uri

### ISSUE THREAD

**Issue by shreekantha** [guusdk/httpfileuploadcomponent#45]
When I request a solt to upload the file, its returning slot download and upload uri with port.
I have done proxy-path config for those ports because I dont want to expose those ports to public,
But getSlot method returning with ports.

Please see the response object below

{
    "type": "slot",
    "download": "**https://communicationqa.dhi-edu.com:**7443**/**httpfileupload/ZmbOvMB8HQI5Bjfzp1W5MzFmQ0Y/018902.pdf",
    "upload": {
        "url": "**https://communicationqa.dhi-edu.com:7443**/httpfileupload/ZmbOvMB8HQI5Bjfzp1W5MzFmQ0Y/018902.pdf"
    }
}

Please help how to avoid ports as part of download and upload uri

**Comment by guusdk** [comment]
There will always be a port in the URL. You can change the value of the port with the property `announcedWebPort`.

**Comment by shreekantha** [comment]
Thanks for your quick response.

We don't want to make port public, so we used proxy-pass for those ports. Is there any option to exclude port in getSlot responses of upload and download url

**Comment by guusdk** [comment]
Even if you use a proxy, you will always be using a port. If an URL does not explicitly name a port, the default port is used (port 80 for http, or 443 of https).

I do not believe that this component can be configured to _remove_ the port definition from the announced URL - but you can make it equal to a default, so that it works with your proxy.
